### ISSUE TITLE
needs 4.1 support (fr this time)

### ISSUE THREAD

**Issue by MrMage750** [UuuNyaa/blender_mmd_tools#143]
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\operators\fileio.py", line 168, in execute
    self._do_execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\operators\fileio.py", line 187, in _do_execute
    importer_cls().execute(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\pmx\importer.py", line 854, in execute
    self.__assignCustomNormals()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\pmx\importer.py", line 795, in __assignCustomNormals
    mesh.use_auto_smooth = True
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'

this just started happening recently, pmx models import as empties that have no armatures nor shapekeys.

also

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\__init__.py", line 44, in <module>
    auto_load.init()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\properties\pose_bone.py", line 9, in <module>
    from mmd_tools.properties import patch_library_overridable
ImportError: cannot import name 'patch_library_overridable' from 'mmd_tools.properties' (C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\properties\__init__.py)

the addon flat out won't install either, even when using the method others had previously advised. we **really** need 4.1 support. this is just gonna become a sunk cost as long as the dev will be cutting corners in development. if they're not gonna be actively updating this addon to meet blender's latest versions, then they should just abandon this project and leave blender-mmd addons to someone who has the time and energy for such a commitment

**Comment by UuuNyaa** [comment]
Please try [MMD Tools v4.x](https://github.com/UuuNyaa/blender_mmd_tools/releases) and give us feedback.

**Comment by rintrint** [comment]
If you don't like it, just don't use it. Everyone can create a pull request. But you didn't. You just complain without doing anything. Stop complaining. Ask yourself what you can do for the community. If you want to manage this project you can fork your own version.

**Comment by rintrint** [comment]
@UuuNyaa I think you can close all of the [wontfix](https://github.com/UuuNyaa/blender_mmd_tools/labels/wontfix) issues.

**Comment by UuuNyaa** [comment]
@MrMage750 

> the addon flat out won't install either, even when using the method others had previously advised. we really need 4.1 support.

See #117 for reasons not to focus on non-LTS versions like Blender **4.1**.


@rintrint Thank you for your comment 😀
I will close the wontfix issues after waiting a few days.

**Comment by MrMage750** [comment]
"If you don't like it, just don't use it. Everyone can create a pull request. But you didn't. You just complain without doing anything. Stop complaining. Ask yourself what you can do for the community." 

only project managers can open pull requests. think before you open your stupid mouth.

 "If you want to manage this project you can fork your own version."

typical "if you don't like x, make it yourself" ad hominem. you wouldn't tell a movie critic to direct their own film, nor would you tell a food critic to become a world class chef.

**Comment by MrMage750** [comment]
> Please try [MMD Tools v4.x](https://github.com/UuuNyaa/blender_mmd_tools/releases) and give us feedback.

that's literally the one I was using since 4.0...

**Comment by MrMage750** [comment]
> See #117 for reasons not to focus on non-LTS versions like Blender **4.1**. if you can't/won't uphold this project, then abandon it and leave it to someone who is capable of doing so. you're kidding yourself and the blender community by failing to support the latest version of blender, for whatever reason

**Comment by listelin** [comment]
@MrMage750 
> > Please try [MMD Tools v4.x](https://github.com/UuuNyaa/blender_mmd_tools/releases) and give us feedback.
> that's literally the one I was using since 4.0... and it works just fine in 4.0, but it's completely broken in 4.1

As far as I have tried, I think the basic functions of MMD tools 4.0.0pre work with blender 4.1.1. Which specific functions are not working?

>  leave blender-mmd addons to someone who has the time and energy for such a commitment

If there is such a person, he/she should be a collaborator. Everyone is welcome.

I understand that you want to support this as soon as possible, but you can open a blend file that imported mmd model/motion in 3.6 with 4.1.

I think it would be nice to have a little more respect for the open source developers who put a lot of effort into this.

**Comment by listelin** [comment]
@MrMage750 
> that's literally the one I was using since 4.0... and it works just fine in 4.0

Which ones exactly do you mean by "works in 4.0 but not in 4.1"?

**Comment by rintrint** [comment]
The project is for free. Again, if you don't like it just uninstall it. You can choose which movie you watch. You can choose which addon you install. And you didn't pay for this project. No one owes anything to you. You don't know how to use the power of an open source project. You don't even know how to use GitHub. That's why you can't do anything instead of complaint.

Anyone can be project collaborator. But it seems like you don't have the ability to contribute to this project. That's fine. Don't be sad. Those who have can just fork their own version or create a PR. Your complaint and abuse won't change anything. You should know who is actually stupid. HAHA

You know what's the truth? The people who can contribute do not have time. And they don't want to hear some stupid people keep complaining without doing anything. The people who can't contribute just keep complaining. If you keep your attitude like this, no one will be willing to do anything for you.

**Comment by MrMage750** [comment]
> The project is for free. Again, if you don't like it just uninstall it. You can choose which movie you watch. You can choose which addon you install. And you didn't pay for this project. No one owes anything to you. You don't know how to use the power of an open source project. You don't even know how to use GitHub. That's why you can't do anything instead of complaint.

now you're resorting to credentialism. a project being free/open source is no excuse to cut corners in it's design.

> Anyone can be project collaborator. But it seems like you don't have the ability to contribute to this project. That's fine. Don't be sad. Those who have can just fork their own version or create a PR. Your complaint and abuse won't change anything. You should know who is actually stupid. HAHA

I doubt that someone who doesn't give positive criticism and resorts to appeal to authority fallacy 24/7 counts as "anyone". and you call me stupid, yet you're clearly another hive animal in the blender community who has no sense of free thought at all,

> You know what's the truth? The people who can contribute do not have time. And they don't want to hear some stupid people keep complaining without doing anything. The people who can't contribute just keep complaining. If you keep your attitude like this, no one will be willing to do anything for you.

there you go again pointing fingers at me while being no better yourself. and I see you're a contribution nut as well. the truth is that UuuNyaa is going complacent with the vast majority of users failing to give any actual criticism, which will ultimately lead to this Uuunyaa, and their project, falling flat on the ground, and never getting back up

**Comment by MrMage750** [comment]
> As far as I have tried, I think the basic functions of MMD tools 4.0.0pre work with blender 4.1.1. Which specific functions are not working?

pretty much everything in 4.1.0

> If there is such a person, he/she should be a collaborator. Everyone is welcome.

he/she should be the owner/author in such a case
 
> I understand that you want to support this as soon as possible, but you can open a blend file that imported mmd model/motion in 3.6 with 4.1.

if this project was properly maintained, I wouldn't have to subject myself to such needless extra work

> I think it would be nice to have a little more respect for the open source developers who put a lot of effort into this.

what effort?

**Comment by MrMage750** [comment]
> Which ones exactly do you mean by "works in 4.0 but not in 4.1"?

as in the addon is fully functional in 4.0.2, but broken in 4.1.0

**Comment by listelin** [comment]
> > As far as I have tried, I think the basic functions of MMD tools 4.0.0pre work with blender 4.1.1. Which specific functions are not working?
> 
> pretty much everything in 4.1.0

For example, what kind of error or behavior do you get when you import pmx?
Maybe there is something wrong that has nothing to do with mmd tools.

**Comment by listelin** [comment]
> > Which ones exactly do you mean by "works in 4.0 but not in 4.1"?
> 
> as in the addon is fully functional in 4.0.2, but broken in 4.1.0

which addon? version ?
Is  it mmd tools to begin with? Is it another add-on you are talking about?

**Comment by MrMage750** [comment]
> For example, what kind of error or behavior do you get when you import pmx? Maybe there is something wrong that has nothing to do with mmd tools.

scroll up

**Comment by MrMage750** [comment]
> as in the addon is fully functional in 4.0.2, but broken in 4.1.0

> which addon? version ? Is it mmd tools to begin with? Is it another add-on you are talking about?

yeah I'm using the latest version of blendersourcetools on blender 2.7.0 🤦‍♂️

let's get real here, even someone of below average intelligence would intentionally keep things relevant on any github discussion. I'm using the latest version of mmdtools on 4.1.0, not necessarily the latest version of blender, but if it is 4.1.1, then it shouldn't make a difference since the third digit in a program's version normally only has a few patches, and/or any other minor differences

**Comment by listelin** [comment]
@MrMage750 
Please clarify your comments.
1. What kind of error or behavior do you get when you import pmx?
2. Which ones exactly do you mean by "works in 4.0 but not in 4.1"?

**Comment by MrMage750** [comment]
> @MrMage750 Please clarify your comments.
> 
> 1. What kind of error or behavior do you get when you import pmx?

god forbid you scroll up a few hundred dots and look at the OP

> Traceback (most recent call last):
 File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\operators\fileio.py", line 168, in execute
 self._do_execute(context)
 File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\operators\fileio.py", line 187, in _do_execute
 importer_cls().execute(
 File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\pmx\importer.py", line 854, in execute
 self.__assignCustomNormals()
 File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\pmx\importer.py", line 795, in __assignCustomNormals
 mesh.use_auto_smooth = True
 ^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'


> 2. Which ones exactly do you mean by "works in 4.0 but not in 4.1"?

the sole addon this entire github page is based on: mmdtools, and the latest version of the addon. as in that version of the addon is fully functional in 4.0.1, but has zero functionality in 4.1.0

**Comment by MrMage750** [comment]
for additional context, this error occurs with any pmx model, even ones that import just fine in 4.0.1, and prior, so this isn't a model specific issue

**Comment by listelin** [comment]
@MrMage750 
> god forbid you scroll up a few hundred dots and look at the OP
It should not be V4.0.0.

If there is no problem, I think this issue should be closed, don't you?

**Comment by MrMage750** [comment]
> @MrMage750
> 
> > god forbid you scroll up a few hundred dots and look at the OP
> 
> It should not be V4.0.0.
> 
> If there is no problem, I think this issue should be closed, don't you?

elaborate. afaik, v4.0.0 is the latest version of the addon, and has been since the addon got 4.0 support

**Comment by listelin** [comment]
@MrMage750 
I am having trouble understanding what you are talking about at all.
v4.0.0 was not released 5 days ago when you wrote this issue.

Which add-ons work with blender 4.0 and which do not work with blender 4.1?

**Comment by MrMage750** [comment]
> @MrMage750 I am having trouble understanding what you are talking about at all. v4.0.0 was not released 5 days ago when you wrote this issue.
> 
> Which add-ons work with blender 4.0 and which do not work with blender 4.1?

hold on. I was almost certain 4.0.0 has been around longer than that. but let me try a fresh install of that and try it in blender 4.1.0

**Comment by listelin** [comment]
@MrMage750 
As UuuNyaa commented above, this is v4.0.0 https://github.com/UuuNyaa/blender_mmd_tools/releases/tag/v4.0.0

If you haven't tried this, could you try it?
If you get an error, please be specific.

**Comment by MrMage750** [comment]
> @MrMage750 As UuuNyaa commented above, this is v4.0.0 https://github.com/UuuNyaa/blender_mmd_tools/releases/tag/v4.0.0
> 
> If you haven't tried this, could you try it? If you get an error, please be specific.

this is confusing as hell. I did a clean install and everything is working just fine. I was doing the exact same thing before I open this and it wasn't, so I'm at wit's end on why it's all of a sudden working again

**Comment by MrMage750** [comment]
but either way, this entire flame war was redundant and I was wrong about *most* of what I said here. specifically about the dev and the addon

**Comment by MrMage750** [comment]
but it will forever baffle me on why this addon was bricked one install and just fine on another, while still being the exact same thing
